"""Added marked deleted on in userchannelmapping table

Revision ID: 45f84cafc4bd
Revises: 338314ac2498
Create Date: 2016-07-22 21:49:11.781888

"""

# revision identifiers, used by Alembic.
revision = '45f84cafc4bd'
down_revision = '338314ac2498'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channel_mapping', sa.Column('marked_deleted_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_channel_mapping', 'marked_deleted_on')
    ### end Alembic commands ###
