"""Added user_new table

Revision ID: 5f3a25d59fa2
Revises: bc11fb454644
Create Date: 2016-07-10 12:46:15.593841

"""

# revision identifiers, used by Alembic.
revision = '5f3a25d59fa2'
down_revision = 'bc11fb454644'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
