"""Added Invitation table

Revision ID: 73aad3b4f514
Revises: 45f84cafc4bd
Create Date: 2016-07-27 10:12:31.550346

"""

# revision identifiers, used by Alembic.
revision = '73aad3b4f514'
down_revision = '45f84cafc4bd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_join_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('requested_for', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_on', sa.DateTime(), nullable=True),
    sa.Column('rejected_on', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_join_request')
    ### end Alembic commands ###
