"""Added user table

Revision ID: bc11fb454644
Revises: dab824ac7c12
Create Date: 2016-07-10 12:41:26.719017

"""

# revision identifiers, used by Alembic.
revision = 'bc11fb454644'
down_revision = 'dab824ac7c12'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
