"""Added user channel mapping table

Revision ID: c7ec268c1001
Revises: 8482e883fa57
Create Date: 2016-07-18 00:07:58.464879

"""

# revision identifiers, used by Alembic.
revision = 'c7ec268c1001'
down_revision = '8482e883fa57'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channel_mapping',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_channel_mapping')
    ### end Alembic commands ###
