"""Created user table

Revision ID: dab824ac7c12
Revises: dd5b57c2de0c
Create Date: 2016-07-10 12:28:41.034415

"""

# revision identifiers, used by Alembic.
revision = 'dab824ac7c12'
down_revision = 'dd5b57c2de0c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
