"""first alembic revision

Revision ID: dd5b57c2de0c
Revises: 
Create Date: 2016-07-10 12:07:21.719379

"""

# revision identifiers, used by Alembic.
revision = 'dd5b57c2de0c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
